---
title: ESS 330 Final Project
authors:
  - name: Sara McLaughlin
    affiliation: Colorado State University
    roles: writing
    corresponding: true
    
  - name: Stephanie Farmer
    affiliation: Colorado State University
    roles: writing
    
  - name: Kiara Gleiser Gherson
    affiliation: Colorado State University
    roles: writing
    
bibliography: references.bib
csl: apa.csl
---
# 1. Title:
# The Effects of Sea Level Rise on Freshwater Quality Within the State of Florida from 2010 - 2024  

# 2. Introduction:
# Sea Level rise has had significant impacts on water quality. As the sea level increases, saltwater intrusion can contaminate freshwater aquifers which reduce the availability of clean drinking water [@werner2009]. The intrusion of saltwater also degrades wetlands, which act as a natural water filter and are habitats for diverse aquatic species. The decrease in wetlands diminishes their ability to buffer against storm surges and filter pollutants, further compromising the water quality [@dessu2018]. Also, rising sea levels lead to more frequent and severe coastal flooding which can result in an overflow of sewage systems and carry pollutants into waterways. This increase in contamination can endanger public health and harm aquatic ecosystems. Understanding and addressing the effects of sea level rise on water quality is significant for protecting freshwater resources, preserving ecosystems and ensuring the sustainability of coastal communities. Our hypothesis to address this research project is: If sea level rise has increased from 2010 to 2024 in the state of Florida, then the salinity levels in freshwater sources will also have increased, degrading overall freshwater quality. This will require two data sets: (1) sea level data from NOAA’s Tides and Current database and (2) freshwater quality (specifically, salinity) data from the USGS National Water Information System. From this data, we will construct a spearman correlation test to determine correlation, a linear regression model to determine the strength of the relationship, and a scatter plot to visualize the relationship.

# 3. Data: 

# 4. Methods: 
# We will be using a spearman correlation test, linear regression model, and ggplot to analyze our data to answer our research question. I think we do have everything we need for this: sea level rise data (2010-2024 for 18 sites in Florida), water quality (salinity) data (2010-2024 for all guages in Florida). Latitude and longitudes were included for each point of the water quality data. We do need suplimental latitude and longitude data for the sea level rise points to match them with water quality data, but I was able to collect this from NOAA and record them in an excel sheet. I think the most challenging part of this process will be merging the two data sets by location. The way their lat and longitudes were recorded are not identical, and the location data for sea level rise was recorded separately from the actual sea level data which makes this more difficult. I think some potential challenges in the analysis portion of the project that may arise are avoiding other confounding variables as hydrological conditions vary greatly across sites. Also, since this is an observational study, our analysis will only be able to determine correlation instead of causation, which limits the meaning of our results. Our selected tests, however, will be useful in determining our final results. The spearmens correlation test will first determine if there is a correlation between the two variables (sea level rise and salinity). Once we've determined a correlation, the linear regression model will allow us to test the strength of this correlation to determine significance. Finally, employing a scatterplot will be useful for easier visualization of this relationship to confirm our results. 
